// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbE8O08lMJiRjhiTdnVS7MMDLzhsJRcLA',
    appId: '1:722811311943:web:e192591f5877ac2a32de62',
    messagingSenderId: '722811311943',
    projectId: 'pharmaconnect-a1856',
    authDomain: 'pharmaconnect-a1856.firebaseapp.com',
    storageBucket: 'pharmaconnect-a1856.firebasestorage.app',
    measurementId: 'G-76T10DE8DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OLwbGhNAfrh9MbJttpwDK-Mkz5x-YX4',
    appId: '1:722811311943:android:494e645f5fd16eb532de62',
    messagingSenderId: '722811311943',
    projectId: 'pharmaconnect-a1856',
    storageBucket: 'pharmaconnect-a1856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbn4RLjJXD5O2gLgHUtezl9dWxkBlu_7g',
    appId: '1:722811311943:ios:e3a5c7372281a84c32de62',
    messagingSenderId: '722811311943',
    projectId: 'pharmaconnect-a1856',
    storageBucket: 'pharmaconnect-a1856.firebasestorage.app',
    iosBundleId: 'com.example.pharmaConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbn4RLjJXD5O2gLgHUtezl9dWxkBlu_7g',
    appId: '1:722811311943:ios:e3a5c7372281a84c32de62',
    messagingSenderId: '722811311943',
    projectId: 'pharmaconnect-a1856',
    storageBucket: 'pharmaconnect-a1856.firebasestorage.app',
    iosBundleId: 'com.example.pharmaConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbE8O08lMJiRjhiTdnVS7MMDLzhsJRcLA',
    appId: '1:722811311943:web:898a9834596ba96c32de62',
    messagingSenderId: '722811311943',
    projectId: 'pharmaconnect-a1856',
    authDomain: 'pharmaconnect-a1856.firebaseapp.com',
    storageBucket: 'pharmaconnect-a1856.firebasestorage.app',
    measurementId: 'G-0ZC1MNVRT9',
  );
}
